[package]
name = "impeccino-hook"
edition.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
impeccino-common = { workspace = true }
impeccino-core = { workspace = true }
impeccino-detect = { workspace = true }
impeccino-context = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
once_cell = { workspace = true }
sha2 = "0.10"
