#!/usr/bin/env node
// Tags and publishes a GitHub release for one of the independently versioned
// components: skill, cli, engine.
//
// Usage: node scripts/release.mjs <skill|cli|engine> [--dry-run]
//
// `engine` is different: it only tags `engine-v<version>` and pushes the
// tag; .github/workflows/release-engine.yml builds the five binaries and
// publishes the GitHub Release. It has no local artifacts.
//
// Refuses on a dirty tree or an unpushed HEAD. Release notes are generated by
// GitHub from the commits since the previous tag of the same component.
// The skill release is a tag on the commit skill managers pin; it has no
// build and no artifacts (docs/adr/0003).

import { readFileSync, existsSync } from 'node:fs';
import { execSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { checkEngineRelease } from './check-engine-release.mjs';
import { readEngineVersion } from './fetch-engine.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const COMPONENTS = {
  skill: {
    manifest: 'skill/SKILL.md',
    readVersion: readSkillVersion,
    tagPrefix: 'skill-v',
    label: 'Skill',
    // The skill's launcher dead-ends without the engine release for the
    // pinned skill/scripts/VERSION. Enforce release order (D4).
    engineGated: true,
    postReleaseHint: null,
  },
  cli: {
    manifest: 'package.json',
    tagPrefix: 'cli-v',
    label: 'CLI',
    // The npm shim resolves the engine binary through the @impeccable/cli-<os>-<arch>
    // platform packages (pinned at skill/scripts/VERSION) and the dist channel; publishing
    // it before those exist strands `npx impeccable`. Enforce release order (D4).
    engineGated: true,
    postReleaseHint: 'Run `npm publish` next to push the package to the npm registry.',
  },
  engine: {
    // Version comes from skill/scripts/VERSION, the file the launcher reads;
    // releaseEngine() below owns this component's whole flow.
    manifest: 'skill/scripts/VERSION',
    tagPrefix: 'engine-v',
    label: 'Engine',
  },
};

const REPO_URL = 'https://github.com/pbakaus/impeccable';

const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const component = args.find((a) => !a.startsWith('--'));

if (!component || !COMPONENTS[component]) {
  console.error('usage: release.mjs <skill|cli|engine> [--dry-run]');
  process.exit(1);
}
const cfg = COMPONENTS[component];

if (component === 'engine') {
  await releaseEngine();
  process.exit(0);
}

function fail(msg) {
  console.error(`✗ ${msg}`);
  process.exit(1);
}
function ok(msg) {
  console.log(`✓ ${msg}`);
}
function step(msg) {
  console.log(`\n→ ${msg}`);
}
function run(cmd) {
  return execSync(cmd, { cwd: repoRoot, encoding: 'utf8' }).trim();
}
function runMutating(cmd) {
  if (dryRun) {
    console.log(`  [dry-run] ${cmd}`);
    return;
  }
  execSync(cmd, { cwd: repoRoot, stdio: 'inherit' });
}

/** `metadata.version` from SKILL.md frontmatter. */
function readSkillVersion(text) {
  const frontmatter = text.match(/^---\r?\n([\s\S]*?)\r?\n---/)?.[1] ?? '';
  return frontmatter.match(/^metadata:\s*\r?\n(?:[ \t]+.*\r?\n)*?[ \t]+version:\s*["']?([^"'\s]+)/m)?.[1];
}

step(`Reading version from ${cfg.manifest}`);
const manifestText = readFileSync(path.join(repoRoot, cfg.manifest), 'utf8');
const version = cfg.readVersion ? cfg.readVersion(manifestText) : JSON.parse(manifestText).version;
if (!version) fail(`No version field in ${cfg.manifest}`);
ok(`${cfg.label} ${version}`);

// Release-order guard (triage decision D4). Engine-gated components refuse to
// tag/publish until the engine release for the pinned skill/scripts/VERSION is fully
// live: the five engine-v<version> release binaries + .sha256 and the five @impeccable/cli-<os>-<arch>
// npm platform packages. Without this the launcher and the npm shim
// dead-end. Set IMPECCABLE_SKIP_ENGINE_CHECK=1 only
// when you know the assets exist and the registry probe is unreachable.
if (cfg.engineGated && process.env.IMPECCABLE_SKIP_ENGINE_CHECK !== '1') {
  const engineVersion = readEngineVersion(repoRoot);
  step(`Verifying engine v${engineVersion} release assets are published (D4 release-order guard)`);
  const result = await checkEngineRelease({ version: engineVersion });
  if (!result.ok) {
    console.error('✗ Engine release is incomplete. Missing assets:');
    for (const m of result.missing) console.error(`    · ${m.what}\n        ${m.url}`);
    fail(
      `Refusing to release ${cfg.label} ${version}: engine v${engineVersion} is not fully published.\n` +
      `  Publish engine v${engineVersion} (bun run release:engine) AND the five @impeccable/cli-<os>-<arch>\n` +
      '  npm platform packages first. Ordering: engine release → platform packages → skill/CLI release.\n' +
      '  See CLAUDE.md "Releases" and the engine repo docs/REVIEW-TRIAGE.md D4.'
    );
  }
  ok(`engine v${engineVersion} release assets all present`);
} else if (cfg.engineGated) {
  step('Skipping engine release-order guard (IMPECCABLE_SKIP_ENGINE_CHECK=1)');
}

const tag = `${cfg.tagPrefix}${version}`;

step('Checking working tree is clean');
const status = run('git status --porcelain');
if (status) fail(`Working tree is dirty. Commit or stash first:\n${status}`);
ok('clean');

step('Checking HEAD is pushed to origin');
const branch = run('git rev-parse --abbrev-ref HEAD');
const head = run('git rev-parse HEAD');
let remoteHead;
try {
  remoteHead = run(`git rev-parse origin/${branch}`);
} catch {
  fail(`No tracking branch origin/${branch}. Push first.`);
}
if (head !== remoteHead) fail(`HEAD is ahead of origin/${branch}. Push your commits first.`);
ok(`origin/${branch} matches HEAD`);

step(`Verifying tag ${tag} does not already exist`);
let localTagExists = false;
try {
  run(`git rev-parse -q --verify "refs/tags/${tag}"`);
  localTagExists = true;
} catch {}
if (localTagExists) fail(`Tag ${tag} already exists locally.`);
const remoteTags = run('git ls-remote --tags origin');
if (remoteTags.split('\n').some((line) => line.endsWith(`refs/tags/${tag}`))) {
  fail(`Tag ${tag} already exists on origin.`);
}
ok('tag is free');

// Notes come from GitHub: the commits since this component's previous tag.
const previousTag = run(`git tag --list '${cfg.tagPrefix}*' --sort=-v:refname`).split('\n').filter(Boolean)[0] || '';

console.log(`\nRelease notes: generated by GitHub${previousTag ? ` from ${previousTag}` : ''}.\n`);

step(`Creating annotated tag ${tag}`);
runMutating(`git tag -a ${tag} -m "${cfg.label} ${version}"`);
runMutating(`git push origin ${tag}`);

step(`Creating GitHub release ${tag}`);
const notesStart = previousTag ? ` --notes-start-tag ${previousTag}` : '';
runMutating(
  `gh release create ${tag} --title "${cfg.label} ${version}" --generate-notes${notesStart}`
);

console.log(`\n✓ ${cfg.label} ${version} released as ${tag}`);

if (cfg.postReleaseHint) {
  console.log(`\n→ Next step: ${cfg.postReleaseHint}`);
}

// The engine release: verify, tag, push. CI does the building and publishing
// (release-engine.yml), so the maintainer's machine never needs five
// toolchains. The whole workspace builds from source, so there is nothing to
// fetch and nothing to order ahead of it.
async function releaseEngine() {
  step('Reading version from skill/scripts/VERSION');
  const version = readEngineVersion(repoRoot);
  if (!/^\d+\.\d+\.\d+/.test(version)) fail(`skill/scripts/VERSION "${version}" is not a version`);
  ok(`Engine ${version}`);

  step('Checking package.json optionalDependencies pin the same engine version');
  const pkg = JSON.parse(readFileSync(path.join(repoRoot, 'package.json'), 'utf8'));
  const pins = Object.entries(pkg.optionalDependencies || {}).filter(([name]) => name.startsWith('@impeccable/cli-'));
  const wrong = pins.filter(([, range]) => String(range).replace(/^[^\d]*/, '') !== version);
  if (wrong.length) fail(`package.json pins ${wrong.map(([n, r]) => `${n}@${r}`).join(', ')}; expected ${version}. Bump them with skill/scripts/VERSION.`);
  ok(`${pins.length} platform package pins agree`);

  const tag = `${cfg.tagPrefix}${version}`;

  step('Checking working tree is clean');
  const status = run('git status --porcelain');
  if (status) fail(`Working tree is dirty. Commit or stash first:\n${status}`);
  ok('clean');

  step('Checking HEAD is pushed to origin');
  const branch = run('git rev-parse --abbrev-ref HEAD');
  const head = run('git rev-parse HEAD');
  let remoteHead;
  try {
    remoteHead = run(`git rev-parse origin/${branch}`);
  } catch {
    fail(`No tracking branch origin/${branch}. Push first.`);
  }
  if (head !== remoteHead) fail(`HEAD is ahead of origin/${branch}. Push your commits first.`);
  ok(`origin/${branch} matches HEAD`);

  step(`Verifying tag ${tag} does not already exist`);
  let localTagExists = false;
  try {
    run(`git rev-parse -q --verify "refs/tags/${tag}"`);
    localTagExists = true;
  } catch {}
  if (localTagExists) fail(`Tag ${tag} already exists locally.`);
  const remoteTags = run('git ls-remote --tags origin');
  if (remoteTags.split('\n').some((line) => line.endsWith(`refs/tags/${tag}`))) {
    fail(`Tag ${tag} already exists on origin.`);
  }
  ok('tag is free');

  step(`Creating annotated tag ${tag}`);
  runMutating(`git tag -a ${tag} -m "Engine ${version}"`);
  runMutating(`git push origin ${tag}`);

  console.log(`\n✓ Engine ${version} tagged as ${tag}`);
  console.log(`\n→ Next step: watch the release-engine workflow (${REPO_URL}/actions/workflows/release-engine.yml).`);
  console.log(`  It publishes the five binaries + .sha256 as ${REPO_URL}/releases/tag/${tag}.`);
  console.log('  Then publish the five @impeccable/cli-<os>-<arch> npm platform packages with `bun run release:platform-packages`, then release the CLI/skill.');
}
